// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Fetch the signed-in FriendChat user's profile (display name, clipID, bio, level, XP).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: profileError } = await supabase.from("profiles").select("id, clip_id, display_name, bio, avatar_url").eq("id", userId).maybeSingle();
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    const { data: level } = await supabase.from("user_levels").select("level, xp").eq("user_id", userId).maybeSingle();
    const result = { profile, level: level ?? { level: 1, xp: 0 } };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list_friends.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_friends_default = defineTool2({
  name: "list_friends",
  title: "List friends",
  description: "List the signed-in user's accepted friendships with display names and clipIDs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("friendships").select("id, status, user_id, friend_id, created_at").or(`user_id.eq.${userId},friend_id.eq.${userId}`).eq("status", "accepted");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const otherIds = (data ?? []).map((r) => r.user_id === userId ? r.friend_id : r.user_id);
    let profiles = [];
    if (otherIds.length > 0) {
      const { data: p } = await supabase.from("profiles").select("id, clip_id, display_name").in("id", otherIds);
      profiles = p ?? [];
    }
    return {
      content: [{ type: "text", text: JSON.stringify(profiles, null, 2) }],
      structuredContent: { friends: profiles }
    };
  }
});

// src/lib/mcp/tools/list_quests.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_quests_default = defineTool3({
  name: "list_my_quests",
  title: "List my quests",
  description: "List the signed-in user's active quest progress with completion status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("user_quest_progress").select("id, quest_id, current_progress, completed_at, claimed_at, quests(title, description, requirement_count, xp_reward, quest_type)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { quests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send_message.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var send_message_default = defineTool4({
  name: "send_chat_message",
  title: "Send chat message",
  description: "Post a message to a FriendChat room as the signed-in user. Room codes are alphanumeric (e.g. 'C6ZC9N').",
  inputSchema: {
    room_code: z.string().regex(/^[A-Za-z0-9]{1,20}$/).describe("Alphanumeric room code."),
    content: z.string().min(1).max(1e4).describe("Message text (1-10000 chars).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ room_code, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await supabase.from("profiles").select("display_name").eq("id", userId).maybeSingle();
    const { data, error } = await supabase.from("messages").insert({
      room_code,
      content,
      sender_id: userId,
      sender_name: profile?.display_name || "User"
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Sent to ${room_code}: ${content}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/recent_messages.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_messages_default = defineTool5({
  name: "get_recent_messages",
  title: "Get recent room messages",
  description: "Fetch the most recent messages from a FriendChat room the user has access to.",
  inputSchema: {
    room_code: z2.string().regex(/^[A-Za-z0-9]{1,20}$/).describe("Alphanumeric room code."),
    limit: z2.number().int().min(1).max(100).optional().describe("How many messages to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ room_code, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("messages").select("id, sender_name, content, created_at").eq("room_code", room_code).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iepuueapgtqoqbmlswlc";
var mcp_default = defineMcp({
  name: "friendchat-mcp",
  title: "FriendChat",
  version: "0.1.0",
  instructions: "Tools for FriendChat: read the signed-in user's profile, friends, and quests; read recent messages in a chat room; and post a message to a room on their behalf. Room codes are short alphanumeric strings (e.g. 'C6ZC9N').",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_friends_default, list_quests_default, recent_messages_default, send_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
